#!/usr/bin/env python3
"""Embed the editable, offline dashboard in ESP32 flash. No dependencies."""
from pathlib import Path
import sys
import gzip

root = Path(__file__).resolve().parents[1]
html = (root / "learning/dashboard.html").read_text()
transport = (root / "learning/dashboard-ble.js").read_text()
html = html.replace('<script src="dashboard-ble.js"></script>', '<script>\n' + transport + '\n</script>')
face = (root / "learning/dashboard-face.js").read_text()
html = html.replace('<script src="dashboard-face.js"></script>', '<script>\n' + face + '\n</script>')
payload = gzip.compress(html.encode("utf-8"), compresslevel=9, mtime=0)
# Normalize gzip OS byte for identical output across Python/platform versions.
payload = payload[:9] + b"\xff" + payload[10:]
rows = [", ".join(f"0x{b:02x}" for b in payload[i:i+16]) for i in range(0, len(payload), 16)]
generated = '// Generated by tools/embed_dashboard.py; edit dashboard.html instead.\n#pragma once\n#include <pgmspace.h>\nstatic const uint8_t OISHIA_DASHBOARD_GZIP[] PROGMEM = {\n  ' + ',\n  '.join(rows) + '\n};\n'
target = root / "learning/OishiaDashboard.h"
if "--check" in sys.argv:
    if not target.exists() or target.read_text() != generated:
        raise SystemExit("Dashboard header is out of date. Run python3 tools/embed_dashboard.py")
    print("Dashboard header matches its sources.")
else:
    target.write_text(generated)
    print(f"Embedded {len(payload)} dashboard bytes")
